services:
  - type: web
    name: pos-react-vite
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_PATH
        value: /var/data/pos.sqlite
    disks:
      - name: pos-data
        mountPath: /var/data
        sizeGB: 1
